"""Changed BookModel.published_at from datetime to int

Revision ID: f790c44b08d3
Revises: e079efae6331
Create Date: 2025-05-16 22:59:58.862137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f790c44b08d3"
down_revision: Union[str, None] = "e079efae6331"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "published_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Integer(),
        postgresql_using='EXTRACT(EPOCH FROM published_at)::INTEGER',
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "published_at",
        existing_type=sa.Integer(),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###
